# Generated by Django 4.0.5 on 2022-06-16 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_myuser_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='level',
            new_name='permission_level',
        ),
    ]
