# Generated by Django 4.0.5 on 2022-06-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.TextField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
