# Generated by Django 4.0.5 on 2022-06-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='test',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
