# Generated by Django 4.0.5 on 2022-06-14 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_buildingimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='building_address', to='buildings.building')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'ordering': ('-created_at',),
            },
        ),
    ]
