# Generated by Django 4.0.5 on 2022-06-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='company',
            field=models.IntegerField(choices=[(0, '-'), (1, 'Pepsi'), (2, 'Coke')], default='0'),
        ),
    ]
