# Generated by Django 4.0.5 on 2022-06-18 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_room_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='test',
        ),
        migrations.AddField(
            model_name='room',
            name='room_coordinates',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='room_layouts', to='buildings.floorlayout'),
            preserve_default=False,
        ),
    ]
