# Generated by Django 4.0.5 on 2022-06-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_buildingimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingimage',
            name='is_feature',
        ),
        migrations.AlterField(
            model_name='buildingimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Please add alternative text', max_length=255, null=True, verbose_name='Alternative'),
        ),
    ]
