# Generated by Django 4.0.5 on 2022-06-16 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_alter_building_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='company',
            field=models.IntegerField(choices=[(0, '-'), (1, 'Pepsi'), (2, 'Coke')], default=0),
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_floor', to='buildings.building')),
            ],
            options={
                'verbose_name_plural': 'Floors',
                'ordering': ('-created_at',),
            },
        ),
    ]
