# Generated by Django 4.0.5 on 2022-06-14 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_remove_buildingimage_is_feature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='building',
            name='ipfs_cover',
        ),
    ]
