# Generated by Django 4.0.5 on 2022-06-18 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_remove_room_test_room_room_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorlayout',
            name='room_coordinates',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='floor',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_layouts', to='buildings.floorlayout'),
        ),
        migrations.AlterField(
            model_name='floorlayout',
            name='wall_coordinates',
            field=models.CharField(max_length=1000),
        ),
    ]
