# Generated by Django 4.0.5 on 2022-06-18 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_floorlayout_room_coordinates_alter_floor_layout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_coordinates',
        ),
    ]
