# Generated by Django 4.0.5 on 2022-06-18 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0006_remove_room_room_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='layout',
        ),
    ]
