# Generated by Django 4.0.5 on 2022-06-18 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0007_remove_floor_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorlayout',
            name='floor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='floor_layout', to='buildings.floor'),
            preserve_default=False,
        ),
    ]
