# Generated by Django 4.0.5 on 2022-06-18 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0008_floorlayout_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floorlayout',
            name='floor',
        ),
    ]
