# Generated by Django 4.0.5 on 2022-06-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0008_room_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='permission_level',
            field=models.IntegerField(default=0),
        ),
    ]
