# Generated by Django 4.0.5 on 2022-06-18 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0009_remove_floorlayout_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='layout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='floor_layouts', to='buildings.floorlayout'),
            preserve_default=False,
        ),
    ]
