# Generated by Django 4.0.5 on 2022-06-18 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0010_floor_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myevent',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_events_room', to='buildings.room'),
        ),
    ]
