# Generated by Django 4.0.5 on 2022-06-17 00:33

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0011_room_my_field_room_my_field2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='my_field',
        ),
        migrations.RemoveField(
            model_name='room',
            name='my_field2',
        ),
        migrations.AddField(
            model_name='room',
            name='permission_company',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, '-'), (1, 'Pepsi'), (2, 'Coke')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
