# Generated by Django 4.0.5 on 2022-06-17 00:33

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0012_remove_room_my_field_remove_room_my_field2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='permission_company',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Pepsi'), (2, 'Coke')], max_length=2),
        ),
    ]
