# Generated by Django 4.0.5 on 2022-06-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0013_alter_myevent_attendee_alter_myevent_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='myevent',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
