# Generated by Django 4.0.5 on 2022-06-18 21:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buildings', '0014_myevent_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myevent',
            name='attendee',
            field=models.ManyToManyField(blank=True, related_name='my_event_attendees', to=settings.AUTH_USER_MODEL),
        ),
    ]
